### ISSUE TITLE
Westeros Error: unable to create socket name (test0)

### ISSUE THREAD

**Issue by cdelsordo** [rdkcmf/westeros#17]
@jeffwannamaker  I work at CommScope on RDKV applications and we are migrating one of our RDKV embedded applications to run as an RDK Downloadable application.  In order to that we need to migrate away from using the Nexus Surface Compositor (nxpl)  calls to become a westeros compositor client.   I used the test-simpleshell.cpp as an example.
Here is a list of calls I am making
1.	createWesterosClient::WstCompositorCreate which is successful SUCCESS
2.	createWesterosClient WstCompositorSetDisplayName which comes back SUCCESSFUL
3.	createWesterosClient WstCompositorSetRendererModule using libwesteros_render_gl.so which comes back SUCCESSFUL – we do not wish to work in nested mode.
4.	Then call createWesterosClient WstCompositorStart using the display name and get the following failure
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Info: waiting for compositor test0 to start...
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Debug: calling wl_display_create
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Debug: wl_display=0xb2c00470
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Error: unable to create socket name (test0)
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Debug: display: test0 terminating...
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Info: start of compositor test0 has failed
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: WstCompositorStart failed errorError. Compositor thread failed to create display

Seems wl_display_create inside the westeros server is failing and I do not know why.  I was wondering if there were some pointers you could provide. The middleware is RDK-Next and uses Broadcom URSR 19.2. 
Thank you!!
Chris Del Sordo

**Comment by jeffwannamaker** [comment]
Do you have XDG_RUNTIME_DIR env var defined to point to a non-writable location?

If I set XDG_RUNTIME_DIR=/home/root on a device where that folder is read-only I get this:

Westeros Info: waiting for compositor main0 to start...
Westeros Debug: calling wl_display_create
Westeros Debug: wl_display=0xb1a00470
unable to open lockfile /home/root//main0.lock check permissions
Westeros Error: unable to create socket name (main0)
Westeros Debug: display: main0 terminating...
Westeros Info: start of compositor main0 has failed


From: cdelsordo ***@***.***>
Reply-To: rdkcmf/westeros ***@***.***>
Date: Thursday, March 25, 2021 at 10:40 AM
To: rdkcmf/westeros ***@***.***>
Cc: "Wannamaker, Jeff" ***@***.***>, Mention ***@***.***>
Subject: [rdkcmf/westeros] Westeros Error: unable to create socket name (test0) (#17)


@jeffwannamaker<https://urldefense.com/v3/__https:/github.com/jeffwannamaker__;!!CQl3mcHX2A!SoB2A2Pn9FtjpYJW0tfau6bNrBE2U1I4KO_0zqAJZ7UBjM6QWYn9pPG-DQvBZJIgfM-aZLJJ$> I work at CommScope on RDKV applications and we are migrating one of our RDKV embedded applications to run as an RDK Downloadable application. In order to that we need to migrate away from using the Nexus Surface Compositor (nxpl) calls to become a westeros compositor client. I used the test-simpleshell.cpp as an example.
Here is a list of calls I am making

  1.  createWesterosClient::WstCompositorCreate which is successful SUCCESS
  2.  createWesterosClient WstCompositorSetDisplayName which comes back SUCCESSFUL
  3.  createWesterosClient WstCompositorSetRendererModule using libwesteros_render_gl.so which comes back SUCCESSFUL – we do not wish to work in nested mode.
  4.  Then call createWesterosClient WstCompositorStart using the display name and get the following failure
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Info: waiting for compositor test0 to start...
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Debug: calling wl_display_create
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Debug: wl_display=0xb2c00470
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Error: unable to create socket name (test0)
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Debug: display: test0 terminating...
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: Westeros Info: start of compositor test0 has failed
Mar 24 21:48:37 vip78x2w avcsvrmgr[2362]: WstCompositorStart failed errorError. Compositor thread failed to create display

Seems wl_display_create inside the westeros server is failing and I do not know why. I was wondering if there were some pointers you could provide. The middleware is RDK-Next and uses Broadcom URSR 19.2.
Thank you!!
Chris Del Sordo

**Comment by cdelsordo** [comment]
Jeff,
Thank you that worked.
The next question I have is regarding the call WstCompositorSetRendererModule( wctx, "libwesteros_render_gl.so" ).   I am not in need of a nested compositor configuration for my application.  But for RDKV on a Broadcom based board do I need to use libwesteros_render_gl.so or libwesteros_render_nexus.so for this call.
Thank you very much for your help!!
Chris

________________________________

**Comment by cdelsordo** [comment]
Initial issue is resolved.  I will open up a new issue when i have another question.

**Comment by jeffwannamaker** [comment]
Hi Chris,

On a Broadcom based board, if you are creating a ‘normal’ compositor rather than a nested or embedded compositor, you would choose libwesteros_render_nexus.so if you want to use the 2D graphics core rather than the 3D graphics core.

-Jeff

From: cdelsordo ***@***.***>
Reply-To: rdkcmf/westeros ***@***.***>
Date: Friday, March 26, 2021 at 12:15 PM
To: rdkcmf/westeros ***@***.***>
Cc: "Wannamaker, Jeff" ***@***.***>, Mention ***@***.***>
Subject: Re: [rdkcmf/westeros] Westeros Error: unable to create socket name (test0) (#17)

Jeff,
Thank you that worked.
The next question I have is regarding the call WstCompositorSetRendererModule( wctx, "libwesteros_render_gl.so" ). I am not in need of a nested compositor configuration for my application. But for RDKV on a Broadcom based board do I need to use libwesteros_render_gl.so or libwesteros_render_nexus.so for this call.
Thank you very much for your help!!
Chris

________________________________
